# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\Hello Kitty\Desktop\PSoC\Old 381 Labs\PSoC Creator\blink_led\Lab00.cydsn\Lab00.cyprj
# Date: Thu, 12 Jan 2023 19:46:39 GMT
#set_units -time ns
create_clock -name {CyRouted1} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/dsi_in_0}]]
create_clock -name {CyILO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyLFClk} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyIMO} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFClk} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySysClk} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/sysclk}]]


# Component constraints for C:\Users\Hello Kitty\Desktop\PSoC\Old 381 Labs\PSoC Creator\blink_led\Lab00.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\Hello Kitty\Desktop\PSoC\Old 381 Labs\PSoC Creator\blink_led\Lab00.cydsn\Lab00.cyprj
# Date: Thu, 12 Jan 2023 19:46:36 GMT
