<<<<<<< HEAD
<<<<<<< HEAD:Lab 3 - Simon Game/Project/Backup/ECE381_SP23_Lab03_Simon_Clone.4.4/Project/Design01.cydsn/Generated_Source/PSoC4/cyfitter_cfg.h
=======
<<<<<<< HEAD
<<<<<<< HEAD:Lab 3 - Simon Game/Project/Backup/ECE381_SP23_Lab03_Simon_Clone.4.4/Project/Design01.cydsn/Generated_Source/PSoC4/cyfitter_cfg.h
=======
<<<<<<< HEAD:Lab 3 - Simon Game/Project/Design01.cydsn/Generated_Source/PSoC4/cyfitter_cfg.h
/*******************************************************************************
* File Name: cyfitter_cfg.h
* 
* PSoC Creator  4.2
*
* Description:
* This file provides basic startup and mux configuration settings
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef CYFITTER_CFG_H
#define CYFITTER_CFG_H

#include "cytypes.h"

extern void cyfitter_cfg(void);

/* Analog Set/Unset methods */


#endif /* CYFITTER_CFG_H */

/*[]*/
=======
>>>>>>> d64eda67b547499d1a0cb642e2e449ca8147df5e
>>>>>>> e23e5a7dadfbff1500a361091d478f7823854aed
/*******************************************************************************
* File Name: cyfitter_cfg.h
* 
* PSoC Creator  4.4
*
* Description:
* This file provides basic startup and mux configuration settings
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef CYFITTER_CFG_H
#define CYFITTER_CFG_H

#include "cytypes.h"

extern void cyfitter_cfg(void);

/* Analog Set/Unset methods */


#endif /* CYFITTER_CFG_H */

/*[]*/
<<<<<<< HEAD
=======
<<<<<<< HEAD
>>>>>>> e23e5a7dadfbff1500a361091d478f7823854aed
=======
/*******************************************************************************
* File Name: cyfitter_cfg.h
* 
* PSoC Creator  4.2
*
* Description:
* This file provides basic startup and mux configuration settings
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef CYFITTER_CFG_H
#define CYFITTER_CFG_H

#include "cytypes.h"

extern void cyfitter_cfg(void);

/* Analog Set/Unset methods */


#endif /* CYFITTER_CFG_H */

/*[]*/
>>>>>>> 8381928c4384acfcb7526ab7a6dd2d315e643534:Lab 3 - Simon Game/Project/Design01.cydsn/Generated_Source/PSoC4/cyfitter_cfg.h
<<<<<<< HEAD
=======
=======
>>>>>>> e6b66f492be45cb54e7efb6d0f687a534db08ab8:Lab 3 - Simon Game/Project/Backup/ECE381_SP23_Lab03_Simon_Clone.4.4/Project/Design01.cydsn/Generated_Source/PSoC4/cyfitter_cfg.h
>>>>>>> d64eda67b547499d1a0cb642e2e449ca8147df5e
>>>>>>> e23e5a7dadfbff1500a361091d478f7823854aed
