/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "R0.h"
#include "R0_aliases.h"
#include "R1.h"
#include "R1_aliases.h"
#include "R2.h"
#include "R2_aliases.h"
#include "R3.h"
#include "R3_aliases.h"
#include "C0.h"
#include "C0_aliases.h"
#include "C1.h"
#include "C1_aliases.h"
#include "C2.h"
#include "C2_aliases.h"
#include "C3.h"
#include "C3_aliases.h"
#include "LCD.h"
#include "LCD_LCDPort.h"
#include "LCD_LCDPort_aliases.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyDMA.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

