/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "ADC.h"
#include "ADC_IN.h"
#include "ADC_IN_aliases.h"
#include "R_LED.h"
#include "R_LED_aliases.h"
#include "MOTOR.h"
#include "MOTOR_aliases.h"
#include "ADC_ISR.h"
#include "SW.h"
#include "SW_aliases.h"
#include "SW_ISR.h"
#include "LCD.h"
#include "ADC_IRQ.h"
#include "ADC_intClock.h"
#include "LCD_LCDPort.h"
#include "LCD_LCDPort_aliases.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "cy_em_eeprom.h"
#include "CyDMA.h"
#include "CyLFClk.h"

/*[]*/

