/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "UART.h"
#include "UART_SPI_UART.h"
#include "UART_PINS.h"
#include "UART_SPI_UART_PVT.h"
#include "UART_PVT.h"
#include "UART_BOOT.h"
#include "BTN.h"
#include "BTN_aliases.h"
#include "ENC.h"
#include "ENC_aliases.h"
#include "LED_PWM.h"
#include "SPEAKER_PWM.h"
#include "SPEAKER.h"
#include "SPEAKER_aliases.h"
#include "LED_SEL.h"
#include "PWM_CLK.h"
#include "R_LED.h"
#include "R_LED_aliases.h"
#include "G_LED.h"
#include "G_LED_aliases.h"
#include "B_LED.h"
#include "B_LED_aliases.h"
#include "Y_LED.h"
#include "Y_LED_aliases.h"
#include "Motor.h"
#include "PhsBNeg.h"
#include "PhsBNeg_aliases.h"
#include "PhsBPos.h"
#include "PhsBPos_aliases.h"
#include "PhsANeg.h"
#include "PhsANeg_aliases.h"
#include "PhsAPos.h"
#include "PhsAPos_aliases.h"
#include "BTN_ISR.h"
#include "ENC_ISR.h"
#include "RTC_INT.h"
#include "RTC_INT_aliases.h"
#include "RTC_INT_ISR.h"
#include "RTC_COT_IN.h"
#include "RTC_COT_IN_aliases.h"
#include "I2C.h"
#include "I2C_I2C.h"
#include "I2C_PINS.h"
#include "I2C_I2C_PVT.h"
#include "I2C_PVT.h"
#include "I2C_BOOT.h"
#include "UART_SCBCLK.h"
#include "UART_tx.h"
#include "UART_tx_aliases.h"
#include "UART_rx.h"
#include "UART_rx_aliases.h"
#include "I2C_SCBCLK.h"
#include "I2C_sda.h"
#include "I2C_sda_aliases.h"
#include "I2C_scl.h"
#include "I2C_scl_aliases.h"
#include "I2C_SCB_IRQ.h"
#include "cy_em_eeprom.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyDMA.h"
#include "CyLFClk.h"

/*[]*/

