# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\Hello Kitty\Documents\PSoC Creator\Lab02 - Interrupts\Lab02 - Interrupts.cydsn\Lab02 - Interrupts.cyprj
# Date: Thu, 26 Jan 2023 19:58:11 GMT
#set_units -time ns
create_clock -name {CLK(FFB)} -period 83.333333333333329 -waveform {0 41.6666666666667} [list [get_pins {ClockBlock/ff_div_11}]]
create_clock -name {CyRouted1} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/dsi_in_0}]]
create_clock -name {CyILO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyLFClk} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyIMO} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFClk} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySysClk} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/sysclk}]]
create_generated_clock -name {CLK} -source [get_pins {ClockBlock/hfclk}] -edges {1 5 9} [list]


# Component constraints for C:\Users\Hello Kitty\Documents\PSoC Creator\Lab02 - Interrupts\Lab02 - Interrupts.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\Hello Kitty\Documents\PSoC Creator\Lab02 - Interrupts\Lab02 - Interrupts.cydsn\Lab02 - Interrupts.cyprj
# Date: Thu, 26 Jan 2023 19:58:08 GMT
