<<<<<<< HEAD:Lab 3 - Simon Game/Project/Design01.cydsn/Generated_Source/PSoC4/project.h
/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "LED_PWM.h"
#include "LED_SEL.h"
#include "R_LED.h"
#include "R_LED_aliases.h"
#include "G_LED.h"
#include "G_LED_aliases.h"
#include "B_LED.h"
#include "B_LED_aliases.h"
#include "Y_LED.h"
#include "Y_LED_aliases.h"
#include "SPEAKER_PWM.h"
#include "SPEAKER.h"
#include "SPEAKER_aliases.h"
#include "BTN.h"
#include "BTN_aliases.h"
#include "INPUT_TIMER.h"
#include "PRS.h"
#include "PWM_CLK.h"
#include "TIMER_CLK.h"
#include "INPUT_TIMER_ISR.h"
#include "cy_em_eeprom.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyDMA.h"
#include "CyLFClk.h"

/*[]*/

=======
/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "LED_PWM.h"
#include "LED_SEL.h"
#include "R_LED.h"
#include "R_LED_aliases.h"
#include "G_LED.h"
#include "G_LED_aliases.h"
#include "B_LED.h"
#include "B_LED_aliases.h"
#include "Y_LED.h"
#include "Y_LED_aliases.h"
#include "SPEAKER_PWM.h"
#include "SPEAKER.h"
#include "SPEAKER_aliases.h"
#include "BTN.h"
#include "BTN_aliases.h"
#include "INPUT_TIMER.h"
#include "PRS.h"
#include "PWM_CLK.h"
#include "TIMER_CLK.h"
#include "INPUT_TIMER_ISR.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyDMA.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

>>>>>>> e6b66f492be45cb54e7efb6d0f687a534db08ab8:Lab 3 - Simon Game/Project/Backup/ECE381_SP23_Lab03_Simon_Clone.4.4/Project/Design01.cydsn/codegentemp/project.h
