/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "SPI.h"
#include "SPI_SPI_UART.h"
#include "SPI_PINS.h"
#include "SPI_SPI_UART_PVT.h"
#include "SPI_PVT.h"
#include "SPI_BOOT.h"
#include "PWM.h"
#include "LCD.h"
#include "NRF24_IRQ.h"
#include "NRF24_IRQ_aliases.h"
#include "NRF24_CE.h"
#include "NRF24_CE_aliases.h"
#include "PWM_CLK.h"
#include "R_LED.h"
#include "R_LED_aliases.h"
#include "G_LED.h"
#include "G_LED_aliases.h"
#include "B_LED.h"
#include "B_LED_aliases.h"
#include "Y_LED.h"
#include "Y_LED_aliases.h"
#include "PWM_SEL.h"
#include "ENC.h"
#include "ENC_aliases.h"
#include "ENC_ISR.h"
#include "BTN.h"
#include "BTN_aliases.h"
#include "BTN_ISR.h"
#include "SPI_SCBCLK.h"
#include "SPI_sclk_m.h"
#include "SPI_sclk_m_aliases.h"
#include "SPI_miso_m.h"
#include "SPI_miso_m_aliases.h"
#include "SPI_mosi_m.h"
#include "SPI_mosi_m_aliases.h"
#include "SPI_ss0_m.h"
#include "SPI_ss0_m_aliases.h"
#include "SPI_SCB_IRQ.h"
#include "LCD_LCDPort.h"
#include "LCD_LCDPort_aliases.h"
#include "cy_em_eeprom.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyDMA.h"
#include "CyLFClk.h"

/*[]*/

